### ISSUE TITLE
Type hinting incoherence for exceptions

### ISSUE THREAD

**Issue by Soullivaneuh** [php-http/mock-client#22]
| Q            | A
| ------------ | ---
| Bug?         | no
| New Feature? | no
| Version      | v1.0.1

On the `exceptions` property: https://github.com/php-http/mock-client/blob/7b4744017d833f61010dd297644e06bd5996be81/src/Client.php#L42-L45

The type hinting corresponds to `Http\Client\Exception`

But on the adder: https://github.com/php-http/mock-client/blob/7b4744017d833f61010dd297644e06bd5996be81/src/Client.php#L74-L82

It corresponds to `\Exception`.

AFAIK, it makes no sense. Which one should be choose?

I may add a PR after getting #21 merged.

**Comment by Nyholm** [comment]
Using `Http\Client\Exception` is the correct one since clients MUST NOT throw exceptions that does not implement this interface.

**Comment by dbu** [comment]
lets change the typehint on the private field, to not lie. but lets also add a comment that according to the spec this must be a http exception. changing the add method would be a bc break, and if people use custom plugins they might deliberately violate the contract, so it seems to me there are use cases for it. want to do a PR @Soullivaneuh

**Comment by Soullivaneuh** [comment]
@dbu In this case, why not trigger a deprecation error if the passed parameter is something else than a `Http\Client\Exception` instance and move the typing on a next major?

**Comment by dbu** [comment]
deprecation warning is a good idea, yes.
