### ISSUE TITLE
Support HTTPlug 2 (and PSR-18)

### ISSUE THREAD

**Issue by Jean85** [php-http/mock-client#26]
| Q            | A
| ------------ | ---
| Bug?         | no
| New Feature? | yes

#### Actual Behavior
Package is currently not compatible with HTTPlug 2

#### Expected Behavior
Editing the `composer.json` constraint to allow it

#### Possible Solutions
This issue until a new release of php-http/client-common will support HTTPlug 2 too, so it is blocked by https://github.com/php-http/client-common/pull/114

**Comment by Nyholm** [comment]
Wohoo! 
Dev-master and not-yet-released 1.2 will support this

**Comment by JaZo** [comment]
@Nyholm, when can we expect 1.2 to be released? Are there any outstanding issues that need to be resolved? I'm waiting for a HTTPlug 2 compatible release so I can update [swisnl/php-http-fixture-client](https://github.com/swisnl/php-http-fixture-client) to make it compatible with HTTPlug 2.

**Comment by dbu** [comment]
looking at https://github.com/php-http/mock-client/compare/1.1.0...master i think we are ready to release the mock-client. as long as client-common is not released, you can't have a stable release with httplug 2, but we don't miss much for client-common either.

@Nyholm okay if i tag the mock-client or do we wait for something?

**Comment by Nyholm** [comment]
Im okey with releasing 1.2.0 now. 

A few weeks ago we discussed that we should wait for the release of client-common 2.0. As that work is almost finished I dont see any reason why we could not release 1.2 now.

**Comment by dbu** [comment]
tagged the release
