### ISSUE TITLE
Cannot install mock-client with httpplug 2.0 without lowering stability to dev

### ISSUE THREAD

**Issue by jkobus** [php-http/mock-client#37]
| Q            | A
| ------------ | ---
| Bug?         | yes
| New Feature? | no
| Version      | 1.1.0

#### Actual Behavior

Requiring mock-client in composer fails:

```
Problem 1
    - php-http/mock-client 1.1.0 requires php-http/httplug ^1.0 -> satisfiable by php-http/httplug[v1.0.0, v1.1.0].
    - Can only install one of: php-http/httplug[v2.0.0, v1.0.0].

```

Workaround: `composer require php-http/mock-client:@dev`

In composer.json:

```
    "minimum-stability": "dev",
    "prefer-stable": true,
```

#### Expected Behavior

Requiring mock-client in composer should install the mock-client (stable).

#### Steps to Reproduce

- create default composer configuration file
- run `composer require php-http/httplug` (installs 2.0)
- run `composer require php-http/mock-client` (fails, requires httplug 1.0)

#### Possible Solutions

Tag a release.

**Comment by jkobus** [comment]
Well, no. Now it fails with `php-http/client-common`. 

```
  Problem 1
    - php-http/client-common 1.9.0 requires php-http/httplug ^1.1 -> satisfiable by php-http/httplug[v1.1.0] but these conflict with your requirements or minimum-stability.
    - php-http/mock-client 1.2.0 requires php-http/client-common ^1.9 || ^2.0 -> satisfiable by php-http/client-common[1.9.0].
    - Installation request for php-http/mock-client ^1.2 -> satisfiable by php-http/mock-client[1.2.0].
```

**Comment by jkobus** [comment]
This package is okay so we can close this.

**Comment by xabbuh** [comment]
Thanks for the information.
