### ISSUE TITLE
Implement StrictClient that expects a sequence of requests

### ISSUE THREAD

**Issue by localheinz** [php-http/mock-client#41]
| Q            | A
| ------------ | ---
| Bug?         | no
| New Feature? | yes
| Version      | n/a

#### Actual Behavior

Currently, when using the [`Client`](https://github.com/php-http/mock-client/blob/1.3.0/src/Client.php) and configuring matchers using [`on`()](https://github.com/php-http/mock-client/blob/1.3.0/src/Client.php#L123-L151)

* iterates over all matchers and returns the response or throws the exception from the [matching matcher](https://github.com/php-http/mock-client/blob/1.3.0/src/Client.php#L77-L91)
* throws an exception (when available) from the queue of [exceptions previously added](https://github.com/php-http/mock-client/blob/1.3.0/src/Client.php#L93-L95)
* returns a response (when available) from the queue of [responses previously added](https://github.com/php-http/mock-client/blob/1.3.0/src/Client.php#L97-L99)
* throws a default exception when no request matcher matched the outgoing request and a [default exception has been set](https://github.com/php-http/mock-client/blob/1.3.0/src/Client.php#L101-L103)
* returns a default response when no request matcher matched the outgoing request and no default exception, but a [default response has been set](https://github.com/php-http/mock-client/blob/1.3.0/src/Client.php#L105-L107)
* returns a [response created by the composed request factory](https://github.com/php-http/mock-client/blob/1.3.0/src/Client.php#L110) when no request matcher matched the outgoing request and neither a default exception nor a default response have been set

This is fine, but what if we expect a specific _sequence_ of requests to be sent with matching responses? If we use use the `Client` as it is right now, it's of course possible to define such a sequence.

However, the order in which request are sent does not matter.

What do you think about introducing a `StrictClient`, that allows specifying an exact sequence of matchers, and that

- allows introspecting in the _assert_ phase whether all expected requests have been sent (the (the sequence has been completed)
- throws a specific exception in the _act_  phase when - given a configured sequence of requests - an unexpected request has been sent

I think this could also nicely cover #36.

What do you think?

#### Possible Solutions

I would of course propose a PR if you think such a feature would be a nice addition.

🤓

**Comment by localheinz** [comment]
Just thinking, at least some of the behavior could be implemented with the current `Client` implementation by using assertions in the `RequestMatcher::matches()`.

**Comment by dbu** [comment]
@localheinz did the implementation you use in your project prove useful? you had closed #42 after opening, saying you want to try it out a bit more...

**Comment by localheinz** [comment]
@dbu 

It worked well in that regard that tests failed when 

- requests where not sent out in the expected order
- not all requests where sent out

However, when the `StrictClient` threw exceptions, then, it was not easy to find out why. I had to `var_dump()` the actual request and the request matcher, then.

**Comment by localheinz** [comment]
I'll close this for now.

**Comment by dbu** [comment]
thanks. feel free to open it again if you have further ideas.
