### ISSUE TITLE
ResponseBody on second asyncCall empty

### ISSUE THREAD

**Issue by kaihenkel** [php-http/mock-client#44]
| Q            | A
| ------------ | ---
| Bug?         | yes
| New Feature? | no
| Version      | 1.3.0

#### Actual Behavior

When receiving the same response multiple times the body is only available for the first call. Content on all subsequent calls is an empty String.

#### Expected Behavior

Identical Body-Content for all Requests

#### Steps to Reproduce

    <?php

    namespace Tests\Mocks;

    use GuzzleHttp\Psr7\Request;
    use GuzzleHttp\Psr7\Response;
    use Http\Client\Promise\HttpFulfilledPromise;
    use Http\Message\RequestMatcher\RequestMatcher;
    use Http\Mock\Client;
    use PHPUnit\Framework\TestCase;

    class HttpMockClientTest extends TestCase
    {
        public function testSpecificResponse()
        {
            $client = new Client();

            $result = 'Default Response';
            $client->on(new RequestMatcher('test'),new Response(200, [], $result));

            $this->example($client, $result, 'First Call');
            $this->example($client, $result, 'Second Call');
        }

        public function testDefaultResponse()
        {
            $client = new Client();

            $result = 'Default Response';
            $client->setDefaultResponse(new Response(200, [], $result));

            $this->example($client, $result, 'First Call');
            $this->example($client, $result, 'Second Call');
        }

        private function example($client, $expected, $message)
        {
            /**
             * @var HttpFulfilledPromise $promise
             */
            $promise = $client->sendAsyncRequest(new Request('GET', 'http://example.com/test'));

            $reponse = $promise->wait();
            $actual = $reponse->getBody()->getContents();

            $this->assertEquals($expected, $actual, $message);
        }
    }

**Comment by kaihenkel** [comment]
I have just implemented the same Issue with the synchronous call - same behavior. Is this expected?
My currently working workaround is to implement a callback function that returns a new Response Object every time it is triggered.

**Comment by dbu** [comment]
yes, responses in the MockClient get "used up". there is only a single default response that you can set if you want.

the assumption was that you would not expect the same call to be executed multiple times inside the same operation (aka test unit). if you do, you could register the same matcher & response multiple times.

**Comment by kaihenkel** [comment]
Thank you for that explanation. I would expect that the Response Object is removed after it has been "used up" I will try responding with a Response-Object that always returns a valid content. 
Since everything works as designed i will close this Issue.
