### ISSUE TITLE
Provide virtual package psr/http-client-implementation

### ISSUE THREAD

**Issue by slepic** [php-http/mock-client#56]
Hello,

since `Http\Client\HttpClient` extends `Psr\Http\Client\ClientInterface`, then any implementation of `Http\Client\HttpClient` also provides implementation of `Psr\Http\Client\ClientInterface`.

Therefore `Http\Mock\Client` provides these implementations and so it would be nice if `psr/http-client-implementation` was also added to composer `provide` section (like `php-http/client-implementation` and `php-http/async-client-implementation`).

I am requesting this change because of this issue: https://github.com/chartmogul/chartmogul-php/pull/76
where we need to change dependency from `php-http/client-implementation` to `psr/http-client-implementation` while we want to keep `php-http/mock-client` to be used for mocking.

I am willing to implement this change, but since it involves just 1 line addition, I think it would be better implemented by maintainers while avoiding the forking burden...

**Comment by dbu** [comment]
i find it weird to have a testing tool "provide" those, but we already do it for the php-http implementations so it is consistent to do it for psr.

however, according to composer.json we allow installation with httplug 1.0 which does not implement the psr client interface. options i see:
1. just add the provide and hope people don't end up with weird broken installations. tag as 1.4.2
2. drop httplug 1.0 in the mock client and only support 2.0 from now on. tag as 1.5
3. wait some more time before we do option 2

@Nyholm do you have an opinion? i tend towards 2.

**Comment by rkrx** [comment]
> i find it weird to have a testing tool "provide" those, but we already do it for the php-http implementations so it is consistent to do it for psr.

Normally you would only use this package as `require-dev` in your project anyway and so the question about whether a Mock is allowed to provide an HTTP implementation would be fine from my point of view.

I consider the main use of such a component to be in libraries that do not intend to specify a concrete dependency and need themselves a mock as a substitute for a concrete implementation.

But I also see a certain probability that first-level projects could also use such a Mock for their own test environment, which might weaken the usefulness of `provide`.

But to add a package in between that just opens php-http/mock-client by one provide, so you can use both options, feels wrong too.

**Comment by slepic** [comment]
any updates on this? imo 2 seems like a good choice

**Comment by d5c4b3** [comment]
I have spent the last 4 hours trying to figure out why composer was throwing the `Your requirements could not be resolved to an installable set of packages.` error at me when I was following the [php-http Library Developer documentation](https://docs.php-http.org/en/latest/httplug/library-developers.html#testing-your-library). 

That documentation seems to think this library implements `psr/http-client-implementation`. 

Composer/[Packagist search](https://packagist.org/providers/psr/http-client-implementation) also seems to think that this library implements `psr/http-client-implementation`
![image](https://user-images.githubusercontent.com/8739797/130690360-15b42466-5a44-407b-8648-74933eeb36b4.png)

Either this package needs to implement psr/http-client-implementation or packagist and the php-http documentation need to be updated to reflect reality.

**Comment by dbu** [comment]
hm, indeed. i don't know why packagist finds it in the search, as the package only provides `php-http/client-implementation`, not the psr implementation...

but looking at this again, i think we should indeed simply have it provide the psr implementation as well. it does provide the php-http/client-implementation already and from the doc change, we intended to also provide the psr implementation.

**Comment by dbu** [comment]
see #57
