### ISSUE TITLE
Stable release

### ISSUE THREAD

**Issue by ddeboer** [php-http/mock-client#8]
What needs to be done before a stable release? If we decide that we need some tests (#4) we can do so after the stable release, I guess.

**Comment by sagikazarmark** [comment]
I agree, I can't see any blocker.

Readme/Contributing guide/Code of conduct needs update.

**Comment by dbu** [comment]
do we have something to update those files automatically? or should i just copy them from the current skeleton?

i guess we should decide on #3 before tagging stable?

**Comment by Nyholm** [comment]
We (Mark) copy them as far as I know.

**Comment by sagikazarmark** [comment]
Do we have anything that keeps us from tagging 1.0.0?

**Comment by dbu** [comment]
unless we feel we need to BC break for #3 and its very simple, i would say lets tag. maybe lets just tag anyways and if somebody works on #3 and it needs breaking changes, we can always do a 2.0 if its worth it

**Comment by barryvdh** [comment]
A stable tag would be nice :)

**Comment by greg0ire** [comment]
@dbu please "tag anyway". I'm developing a library and won't be able to run my tests with a version 1 of  `php-http/discovery` because of this. It does not feel safe…

**Comment by dbu** [comment]
see #18

**Comment by greg0ire** [comment]
Love your reactivity!

**Comment by greg0ire** [comment]
Follow-up doc PR : https://github.com/php-http/documentation/pull/181
